<?php

/**
 * BaseArtista
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $genero_id
 * @property string $nombre
 * @property Genero $Genero
 * @property Doctrine_Collection $Albumes
 * 
 * @method integer             getGeneroId()  Returns the current record's "genero_id" value
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method Genero              getGenero()    Returns the current record's "Genero" value
 * @method Doctrine_Collection getAlbumes()   Returns the current record's "Albumes" collection
 * @method Artista             setGeneroId()  Sets the current record's "genero_id" value
 * @method Artista             setNombre()    Sets the current record's "nombre" value
 * @method Artista             setGenero()    Sets the current record's "Genero" value
 * @method Artista             setAlbumes()   Sets the current record's "Albumes" collection
 * 
 * @package    proyectodiscos
 * @subpackage model
 * @author     usuario
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArtista extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('artista');
        $this->hasColumn('genero_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Genero', array(
             'local' => 'genero_id',
             'foreign' => 'id'));

        $this->hasMany('Album as Albumes', array(
             'local' => 'id',
             'foreign' => 'artista_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}