<?php

/**
 * BaseAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $artista_id
 * @property string $nombre
 * @property string $urlComprar
 * @property string $urlSpotify
 * @property Artista $Artista
 * @property Doctrine_Collection $idAlbum
 * 
 * @method integer             getArtistaId()  Returns the current record's "artista_id" value
 * @method string              getNombre()     Returns the current record's "nombre" value
 * @method string              getUrlComprar() Returns the current record's "urlComprar" value
 * @method string              getUrlSpotify() Returns the current record's "urlSpotify" value
 * @method Artista             getArtista()    Returns the current record's "Artista" value
 * @method Doctrine_Collection getIdAlbum()    Returns the current record's "idAlbum" collection
 * @method Album               setArtistaId()  Sets the current record's "artista_id" value
 * @method Album               setNombre()     Sets the current record's "nombre" value
 * @method Album               setUrlComprar() Sets the current record's "urlComprar" value
 * @method Album               setUrlSpotify() Sets the current record's "urlSpotify" value
 * @method Album               setArtista()    Sets the current record's "Artista" value
 * @method Album               setIdAlbum()    Sets the current record's "idAlbum" collection
 * 
 * @package    proyectodiscos
 * @subpackage model
 * @author     usuario
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlbum extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('album');
        $this->hasColumn('artista_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('urlComprar', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('urlSpotify', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Artista', array(
             'local' => 'artista_id',
             'foreign' => 'id'));

        $this->hasMany('Favoritos as idAlbum', array(
             'local' => 'id',
             'foreign' => 'album_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}