<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/04/03 03:16:08

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=proyectodiscos',
  'username' => 'proyectodiscos',
  'password' => 'proyectodiscos',
  'name' => 'doctrine',
)),);
