<?php

/**
 * ArtistaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArtistaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArtistaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Artista');
    }
    
    public function getTodos()
    {
      return $this->createQuery('artista');
    }
    
    public function getFiltradosPorGenero($genero)
    {
      return $this->getTodos()->andWhere('artista.genero_id='.$genero->getId())->execute();
    }
}
