<?php

/**
 * FavoritosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FavoritosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FavoritosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Favoritos');
    }
    
    
}
