<?php

/**
 * GeneroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GeneroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GeneroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Genero');
    }
    
    public function getTodos()
    {
      return $this->createQuery('genero')->execute();
    }
}
