<?php

/**
 * Genero
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    proyectodiscos
 * @subpackage model
 * @author     usuario
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Genero extends BaseGenero
{
}
