<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/04/02 08:00:27

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=proyectodiscos',
  'username' => 'proyectodiscos',
  'password' => 'proyectodiscos',
  'name' => 'doctrine',
)),);
