<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2014/04/03 04:54:00
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrineconnectionlistener' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrinedatabase' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrineconnectionprofiler' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfformdoctrine' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinegenerator' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrinecolumn' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrineexception' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sftesterdoctrine' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfdoctrinecli' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfwidgetformdoctrinechoice' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfdoctrineroutecollection' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineroute' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrinepager' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinebuildtask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinedatadumptask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinebuilddbtask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinebuildfilterstask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinemigratetask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinebuildformstask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildschematask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrineinsertsqltask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinedataloadtask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinebuildmodeltask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinegenerateadmintask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinedqltask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinebasetask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinebuildsqltask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinecreatemodeltables' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedropdbtask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfwebdebugpaneldoctrine' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'swift_doctrinespool' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfvalidatordoctrineunique' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfvalidatordoctrinechoice' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfdoctrinerecordi18nfilter' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrinerecord' => '/home/user/public_html/proyectodiscos/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',

  // project
  'artistaform' => '/home/user/public_html/proyectodiscos/lib/form/doctrine/ArtistaForm.class.php',
  'basealbumform' => '/home/user/public_html/proyectodiscos/lib/form/doctrine/base/BaseAlbumForm.class.php',
  'basegeneroform' => '/home/user/public_html/proyectodiscos/lib/form/doctrine/base/BaseGeneroForm.class.php',
  'baseartistaform' => '/home/user/public_html/proyectodiscos/lib/form/doctrine/base/BaseArtistaForm.class.php',
  'baseformdoctrine' => '/home/user/public_html/proyectodiscos/lib/form/doctrine/BaseFormDoctrine.class.php',
  'generoform' => '/home/user/public_html/proyectodiscos/lib/form/doctrine/GeneroForm.class.php',
  'albumform' => '/home/user/public_html/proyectodiscos/lib/form/doctrine/AlbumForm.class.php',
  'baseform' => '/home/user/public_html/proyectodiscos/lib/form/BaseForm.class.php',
  'basealbumformfilter' => '/home/user/public_html/proyectodiscos/lib/filter/doctrine/base/BaseAlbumFormFilter.class.php',
  'basegeneroformfilter' => '/home/user/public_html/proyectodiscos/lib/filter/doctrine/base/BaseGeneroFormFilter.class.php',
  'baseartistaformfilter' => '/home/user/public_html/proyectodiscos/lib/filter/doctrine/base/BaseArtistaFormFilter.class.php',
  'generoformfilter' => '/home/user/public_html/proyectodiscos/lib/filter/doctrine/GeneroFormFilter.class.php',
  'baseformfilterdoctrine' => '/home/user/public_html/proyectodiscos/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'artistaformfilter' => '/home/user/public_html/proyectodiscos/lib/filter/doctrine/ArtistaFormFilter.class.php',
  'albumformfilter' => '/home/user/public_html/proyectodiscos/lib/filter/doctrine/AlbumFormFilter.class.php',

  // project_model
  'genero' => '/home/user/public_html/proyectodiscos/lib/model/doctrine/Genero.class.php',
  'generotable' => '/home/user/public_html/proyectodiscos/lib/model/doctrine/GeneroTable.class.php',
  'baseartista' => '/home/user/public_html/proyectodiscos/lib/model/doctrine/base/BaseArtista.class.php',
  'basealbum' => '/home/user/public_html/proyectodiscos/lib/model/doctrine/base/BaseAlbum.class.php',
  'basegenero' => '/home/user/public_html/proyectodiscos/lib/model/doctrine/base/BaseGenero.class.php',
  'albumtable' => '/home/user/public_html/proyectodiscos/lib/model/doctrine/AlbumTable.class.php',
  'artista' => '/home/user/public_html/proyectodiscos/lib/model/doctrine/Artista.class.php',
  'album' => '/home/user/public_html/proyectodiscos/lib/model/doctrine/Album.class.php',
  'artistatable' => '/home/user/public_html/proyectodiscos/lib/model/doctrine/ArtistaTable.class.php',

  // application
  'myuser' => '/home/user/public_html/proyectodiscos/apps/frontend/lib/myUser.class.php',

  // modules
);
